server:
  port: 8080
spring:
  application:
    name: course
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/devdojo?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: password
